version: 2.1

executors:
  local-executor:
    docker:
      - image: circleci/node:16  # Base image with Node.js
    working_directory: ~/project1

jobs:
  scan:
    executor: local-executor
    steps:
      - checkout
      - run:
          name: Install Tigera Scanner
          command: |
            curl -Lo tigera-scanner https://installer.calicocloud.io/tigera-scanner/v3.20.0-1.0-18/image-assurance-scanner-cli-linux-amd64
            chmod +x ./tigera-scanner
            sudo mv tigera-scanner /usr/local/bin/
      - run:
          name: Scan Docker Image Locally
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@xxx.xxx.xxx.xxx bash -c ' \
            cd /usr/local/bin/
            ls -a
            ./tigera-scanner
          #command: ./tigera-scanner scan $IMAGE --apiurl https://z2kj9hab-management.calicocloud.io/bast --token $(buildkite-agent secret get token) --output_file scan-result.json

workflows:
  version: 2
  build-and-scan:
    jobs:
      - scan
