version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:2023.10.1  # Use a machine image with Docker pre-installed

jobs:
  pull-and-scan:
    executor: machine-executor
    environment:
      IMAGE_NAME: nginx:latest  # IMAGE NAME HERE
    steps:
      - checkout
      
      # Step 1: Build the Docker image
      - run:
          name: Pull Docker Image
          command: |
            docker pull $IMAGE_NAME

      # Step 1: Set up the environment
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io  # Ensure Docker is available
            curl -Lo tigera-scanner https://installer.calicocloud.io/tigera-scanner/v3.20.0-2.0-9/image-assurance-scanner-cli-linux-amd64
            chmod +x ./tigera-scanner
            ls -a
            ./tigera-scanner scan --image $IMAGE_NAME

      # Step 3: Scan the image with Tigera Scanner
      - run:
          name: Scan Image with Tigera Scanner
          command: |
            ./tigera-scanner scan --image $IMAGE_NAME

workflows:
  version: 2
  build-and-scan-workflow:
    jobs:
      - pull-and-scan
