version: 2.1

executors:
  local-executor:
    docker:
      - image: circleci/python:3.9  # Base image
    working_directory: ~/project

jobs:
  scan:
    executor: local-executor
    steps:
      - run:
          name: Install Tigera Image Scanner
          command: |
            curl -o tigera-scanner https://installer.calicocloud.io/tigera-scanner/v3.20.0-1.0-18/image-assurance-scanner-cli-linux-amd64
            chmod +x tigera-scanner
            sudo mv tigera-scanner /usr/local/bin/
      - run:
          name: Pull Existing Docker Image
          command: |
            docker pull nginx:latest
      - run:
          name: Scan Docker Image
          command: |
            tigera-image-scanner

workflows:
  version: 2
  scan-image:
    jobs:
      - scan
