version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-2004:2023.10.1  # Use a machine image with Docker pre-installed

jobs:
  pull-and-scan:
    executor: machine-executor
    environment:
      IMAGE_NAME: nginx:latest  # IMAGE NAME HERE
    steps:
      - checkout

      # Step 1: Set up the environment
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io  # Ensure Docker is available
            curl -LO https://github.com/tigera/cli/releases/latest/download/tigera-scanner-linux-amd64
            chmod +x tigera-scanner-linux-amd64
            sudo mv tigera-scanner-linux-amd64 /usr/local/bin/tigera-scanner

      # Step 2: Build the Docker image
      - run:
          name: Pull Docker Image
          command: |
            docker pull $IMAGE_NAME

      # Step 3: Scan the image with Tigera Scanner
      - run:
          name: Scan Image with Tigera Scanner
          command: |
            cd /usr/local/bin/tigera-scanner
            tigera-scanner scan --image $IMAGE_NAME

workflows:
  version: 2
  build-and-scan-workflow:
    jobs:
      - pull-and-scan
